#!/bin/bash
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -euxo pipefail

SYSCONFIG_VERSION=sysconfig_1.24.1
SYSCONFIG_USER=~/ti/${SYSCONFIG_VERSION}/
SYSCONFIG_SYSTEM=/opt/ti/${SYSCONFIG_VERSION}/
SYSCONFIG_DL=https://dr-download.ti.com/software-development/ide-configuration-compiler-or-debugger/MD-nsUM6f7Vvb/1.24.1.4189/sysconfig-1.24.1_4189-setup.run

if [ ! -d "$SYSCONFIG_USER" ] && [ ! -d "$SYSCONFIG_SYSTEM" ]; then
    wget "$SYSCONFIG_DL" --tries 4 --no-check-certificate --quiet -c -O /tmp/sysconfig-1.24.1_4189-setup.run
    chmod +x /tmp/sysconfig-1.24.1_4189-setup.run
    /tmp/sysconfig-1.24.1_4189-setup.run --mode unattended
fi

"$(dirname "$0")"/../openthread/script/bootstrap

#overwrite Openthread GCC Version
install_ti_packages_apt()
{
    # apt-get update and install dependencies

    PLATFORM=$(lsb_release -is)
    ARCH=$(arch)

    if [ "$PLATFORM" = "Raspbian" ]; then
        sudo apt-get --no-install-recommends install -y binutils-arm-none-eabi gcc-arm-none-eabi gdb-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
    elif [ "$PLATFORM" = "Ubuntu" ]; then
        sudo apt-get --no-install-recommends install -y bzip2 ca-certificates wget
        (cd /tmp \
            && wget --tries 4 --no-check-certificate -c https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-"$ARCH"-arm-none-eabi.tar.xz \
            && sudo tar xvf arm-gnu-toolchain-12.2.rel1-"$ARCH"-arm-none-eabi.tar.xz -C /opt \
            && rm arm-gnu-toolchain-12.2.rel1-"$ARCH"-arm-none-eabi.tar.xz \
            && sudo ln -s -f /opt/arm-gnu-toolchain-12.2.rel1-"$ARCH"-arm-none-eabi/bin/* /usr/local/bin/.)
    fi
}

echo 'Installing TI toolchain dependencies...'
install_ti_packages_apt

# Apply patch for bootloader backdoor
SCRIPT_PATH=$(pwd)/$(dirname $0)
cd $SCRIPT_PATH/../third_party/ti_simplelink_sdk/repo_cc13xx_cc26xx/
git apply ../../../patch/bootloader-backdoor-custom.patch
cd $SCRIPT_PATH/..

