#!/bin/bash
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -euxo pipefail

readonly OT_BUILDDIR="$(pwd)/build"
readonly OT_OUTPUTDIR="$(pwd)/output"

readonly OT_OPTIONS=(
    "-DOT_COMPILE_WARNING_AS_ERROR=ON"
    "-DOT_COMMISSIONER=ON"
    "-DOT_DHCP6_CLIENT=ON"
    "-DOT_DHCP6_SERVER=ON"
    "-DOT_DNS_CLIENT=ON"
    "-DOT_JOINER=ON"
)

build()
{
    local launchpad="$1"

    rm -rf "$OT_BUILDDIR"
    "$(dirname "$0")"/build "${launchpad}" $@

    mkdir -p $OT_OUTPUTDIR/${launchpad}
    cp $OT_BUILDDIR/bin/* $OT_OUTPUTDIR/${launchpad}
}

main()
{
    export CPPFLAGS="${CPPFLAGS:-} -DNDEBUG"

    rm -rf $OT_OUTPUTDIR

    build CC1352P1_LAUNCHXL "${OT_OPTIONS[@]}"

    build CC1352P_2_LAUNCHXL "${OT_OPTIONS[@]}"

    build CC1352P_4_LAUNCHXL "${OT_OPTIONS[@]}"

    build CC1352R1_LAUNCHXL "${OT_OPTIONS[@]}"

    build CC26X2R1_LAUNCHXL "${OT_OPTIONS[@]}"

    build LP_CC1352P7_1 "${OT_OPTIONS[@]}"

    build LP_CC1352P7_4 "${OT_OPTIONS[@]}"

    build LP_CC2652PSIP "${OT_OPTIONS[@]}"

    build LP_CC2652R7 "${OT_OPTIONS[@]}"

    build LP_CC2652RB "${OT_OPTIONS[@]}"

    build LP_CC2652RSIP "${OT_OPTIONS[@]}"

    build LP_EM_CC1354P10_1 "${OT_OPTIONS[@]}"

    build LP_EM_CC1354P10_6 "${OT_OPTIONS[@]}"

    build LP_EM_CC2340R5 "${OT_OPTIONS[@]}"
    
    build LP_EM_CC2340R53 "${OT_OPTIONS[@]}"
    
    build LP_EM_CC2755P10 "${OT_OPTIONS[@]}"

    build LP_EM_CC2755P20 "${OT_OPTIONS[@]}"
}

main "$@"
